### ISSUE TITLE
imageフォルダの存在確認とファイルのハッシュ値の検査

### ISSUE THREAD

**Issue by 312k** [Ennichi/Ennichi#14]
# 問題の概要
* imageフォルダがないとゲームは強制終了する
# 提案内容
* 解像度判定しているところで、imageファイルの存在とハッシュの検査をしたい
# 既存からのデメリット
* main.cppの行数が増える

**Comment by Esu0** [comment]
それはそのうちやると思う

**Comment by Esu0** [comment]
余裕があったら今やってもいいんじゃない？
